import { Customer, InventoryItem, Ticket, Notification, User, ParentContract, ChildContract } from "./types";
import { addDays, subDays, format } from "date-fns";

const today = new Date();
const formatDate = (date: Date) => format(date, "yyyy-MM-dd");

export const dummyUsers: User[] = [
  {
    id: "USR001",
    email: "admin@satmz.com",
    password: "admin123",
    name: "Rajesh Kumar",
    role: "distributor",
    companyName: "SATMZ Distribution Pvt Ltd",
    phone: "+91-9876500001",
    avatar: null,
    createdAt: "2022-01-01"
  },
  {
    id: "USR002",
    email: "manager@satmz.com",
    password: "manager123",
    name: "Priya Sharma",
    role: "distributor",
    companyName: "SATMZ Distribution Pvt Ltd",
    phone: "+91-9876500002",
    avatar: null,
    createdAt: "2022-03-15"
  },
  {
    id: "USR003",
    email: "reseller1@satmz.com",
    password: "reseller123",
    name: "John Mathew",
    role: "reseller",
    customerId: "CUST001",
    companyName: "Alpha Business Solutions",
    phone: "+91-9876543210",
    avatar: null,
    createdAt: "2023-01-15",
    managedCustomerIds: ["CUST004", "CUST005"],
    upstreamDistributorId: "USR001"
  },
  {
    id: "USR004",
    email: "reseller2@satmz.com",
    password: "reseller123",
    name: "Sarah Wilson",
    role: "reseller",
    customerId: "CUST002",
    companyName: "Beta Corporation",
    phone: "+91-9876543211",
    avatar: null,
    createdAt: "2023-03-20",
    managedCustomerIds: ["CUST006"],
    upstreamDistributorId: "USR001"
  },
  {
    id: "USR005",
    email: "customer1@satmz.com",
    password: "customer123",
    name: "Mike Johnson",
    role: "customer",
    customerId: "CUST003",
    companyName: "Gamma Industries",
    phone: "+91-9876543212",
    avatar: null,
    createdAt: "2023-06-10"
  },
  {
    id: "USR006",
    email: "customer2@satmz.com",
    password: "customer123",
    name: "Amit Patel",
    role: "customer",
    customerId: "CUST004",
    companyName: "Delta Systems",
    phone: "+91-9876543213",
    avatar: null,
    createdAt: "2023-09-01"
  },
  {
    id: "USR007",
    email: "customer3@satmz.com",
    password: "customer123",
    name: "Lisa Chen",
    role: "customer",
    customerId: "CUST005",
    companyName: "Epsilon Tech",
    phone: "+91-9876543214",
    avatar: null,
    createdAt: "2023-10-15"
  },
  {
    id: "USR008",
    email: "customer4@satmz.com",
    password: "customer123",
    name: "David Brown",
    role: "customer",
    customerId: "CUST006",
    companyName: "Zeta Solutions",
    phone: "+91-9876543215",
    avatar: null,
    createdAt: "2023-11-20"
  }
];

export const dummyCustomers: Customer[] = [
  {
    id: "CUST001",
    name: "Alpha Business Solutions",
    email: "contact@alphabiz.com",
    phone: "+91-9876543210",
    address: "123, Tech Park, Andheri East, Mumbai - 400069",
    gstNumber: "27AAAAA0000A1Z5",
    contactPerson: "John Mathew",
    industry: "IT Services",
    createdAt: "2023-01-15",
    status: "active",
    managedBy: "distributor",
    customerType: "reseller"
  },
  {
    id: "CUST002",
    name: "Beta Corporation",
    email: "info@betacorp.com",
    phone: "+91-9876543211",
    address: "456, Business Hub, Connaught Place, New Delhi - 110001",
    gstNumber: "07BBBBB0000B1Z5",
    contactPerson: "Sarah Wilson",
    industry: "Manufacturing",
    createdAt: "2023-03-20",
    status: "active",
    managedBy: "distributor",
    customerType: "reseller"
  },
  {
    id: "CUST003",
    name: "Gamma Industries",
    email: "support@gammaindustries.com",
    phone: "+91-9876543212",
    address: "789, Industrial Area, Whitefield, Bangalore - 560066",
    gstNumber: "29CCCCC0000C1Z5",
    contactPerson: "Mike Johnson",
    industry: "Healthcare",
    createdAt: "2023-06-10",
    status: "active",
    managedBy: "distributor",
    customerType: "end_customer"
  },
  {
    id: "CUST004",
    name: "Delta Systems",
    email: "hello@deltasystems.com",
    phone: "+91-9876543213",
    address: "321, IT Corridor, HITEC City, Hyderabad - 500081",
    gstNumber: "36DDDDD0000D1Z5",
    contactPerson: "Amit Patel",
    industry: "Finance",
    createdAt: "2023-09-01",
    status: "active",
    managedBy: "USR003",
    customerType: "end_customer"
  },
  {
    id: "CUST005",
    name: "Epsilon Tech",
    email: "info@epsilontech.com",
    phone: "+91-9876543214",
    address: "555, Software Park, Pune - 411057",
    gstNumber: "27EEEEE0000E1Z5",
    contactPerson: "Lisa Chen",
    industry: "Software",
    createdAt: "2023-10-15",
    status: "active",
    managedBy: "USR003",
    customerType: "end_customer"
  },
  {
    id: "CUST006",
    name: "Zeta Solutions",
    email: "contact@zetasolutions.com",
    phone: "+91-9876543215",
    address: "888, Tech Valley, Gurgaon - 122001",
    gstNumber: "06ZZZZZ0000Z1Z5",
    contactPerson: "David Brown",
    industry: "Consulting",
    createdAt: "2023-11-20",
    status: "active",
    managedBy: "USR004",
    customerType: "end_customer"
  }
];

export const dummyParentContracts: ParentContract[] = [
  {
    id: "PC001",
    contractNumber: "SATMZ-2024-PC-001",
    customerId: "CUST001",
    customerName: "Alpha Business Solutions",
    title: "Enterprise IT Infrastructure Contract",
    description: "Comprehensive IT infrastructure supply and support agreement",
    startDate: "2024-01-01",
    endDate: formatDate(addDays(today, 365)),
    status: "active",
    totalValue: 5000000,
    createdBy: "USR001",
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
    productIds: ["INV001", "INV002", "INV003", "INV004"],
    childContractIds: ["CC001", "CC002"],
    terms: "Standard enterprise terms and conditions apply.",
    autoRenew: true,
    renewalReminderDays: 60
  },
  {
    id: "PC002",
    contractNumber: "SATMZ-2024-PC-002",
    customerId: "CUST002",
    customerName: "Beta Corporation",
    title: "Data Center Equipment Contract",
    description: "Data center hardware and support services",
    startDate: "2024-02-15",
    endDate: formatDate(addDays(today, 300)),
    status: "active",
    totalValue: 8500000,
    createdBy: "USR001",
    createdAt: "2024-02-15",
    updatedAt: "2024-02-15",
    productIds: ["INV009", "INV010", "INV011"],
    childContractIds: ["CC003", "CC004"],
    terms: "Premium support terms with 24x7 coverage.",
    autoRenew: true,
    renewalReminderDays: 90
  },
  {
    id: "PC003",
    contractNumber: "SATMZ-2024-PC-003",
    customerId: "CUST003",
    customerName: "Gamma Industries",
    title: "Healthcare IT Solutions Contract",
    description: "Medical equipment IT infrastructure",
    startDate: "2024-03-01",
    endDate: formatDate(addDays(today, 45)),
    status: "expiring_soon",
    totalValue: 3200000,
    createdBy: "USR001",
    createdAt: "2024-03-01",
    updatedAt: "2024-03-01",
    productIds: ["INV016", "INV017", "INV018"],
    childContractIds: ["CC005"],
    terms: "Healthcare compliance terms included.",
    autoRenew: false,
    renewalReminderDays: 30
  },
  {
    id: "PC004",
    contractNumber: "ALPHA-2024-PC-001",
    customerId: "CUST004",
    customerName: "Delta Systems",
    title: "Financial Services IT Contract",
    description: "Banking and financial IT infrastructure",
    startDate: "2024-04-01",
    endDate: formatDate(addDays(today, 200)),
    status: "active",
    totalValue: 2500000,
    createdBy: "USR003",
    createdAt: "2024-04-01",
    updatedAt: "2024-04-01",
    productIds: ["INV023", "INV024", "INV025"],
    childContractIds: ["CC006", "CC007"],
    terms: "Financial sector compliance included.",
    autoRenew: true,
    renewalReminderDays: 45
  },
  {
    id: "PC005",
    contractNumber: "ALPHA-2024-PC-002",
    customerId: "CUST005",
    customerName: "Epsilon Tech",
    title: "Software Development Infrastructure",
    description: "Development and testing environment setup",
    startDate: "2024-05-15",
    endDate: formatDate(addDays(today, 15)),
    status: "expiring_soon",
    totalValue: 1800000,
    createdBy: "USR003",
    createdAt: "2024-05-15",
    updatedAt: "2024-05-15",
    productIds: ["INV031", "INV032"],
    childContractIds: ["CC008"],
    terms: "Standard software development terms.",
    autoRenew: false,
    renewalReminderDays: 30
  },
  {
    id: "PC006",
    contractNumber: "BETA-2024-PC-001",
    customerId: "CUST006",
    customerName: "Zeta Solutions",
    title: "Consulting IT Infrastructure",
    description: "IT setup for consulting operations",
    startDate: "2024-06-01",
    endDate: formatDate(subDays(today, 10)),
    status: "expired",
    totalValue: 1200000,
    createdBy: "USR004",
    createdAt: "2024-06-01",
    updatedAt: "2024-06-01",
    productIds: ["INV033", "INV034"],
    childContractIds: ["CC009"],
    terms: "Standard terms.",
    autoRenew: false,
    renewalReminderDays: 30
  }
];

export const dummyChildContracts: ChildContract[] = [
  {
    id: "CC001",
    contractNumber: "SATMZ-2024-CC-001",
    parentContractId: "PC001",
    parentContractNumber: "SATMZ-2024-PC-001",
    customerId: "CUST001",
    type: "AMC",
    title: "Annual Maintenance Contract - Servers",
    description: "Comprehensive AMC for all server equipment",
    startDate: "2024-01-01",
    endDate: formatDate(addDays(today, 365)),
    status: "active",
    value: 500000,
    coverageType: "full",
    responseTime: "4 hours",
    coveredSerialNumbers: ["SRV-2024-001234", "SRV-2024-001235"],
    productIds: [],
    terms: "Annual maintenance covering hardware and software support",
    autoRenew: true,
    renewalReminderDays: 30,
    createdBy: "USR001",
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01"
  },
  {
    id: "CC002",
    contractNumber: "SATMZ-2024-CC-002",
    parentContractId: "PC001",
    parentContractNumber: "SATMZ-2024-PC-001",
    customerId: "CUST001",
    type: "License",
    title: "Microsoft 365 License Agreement",
    description: "Enterprise M365 licenses",
    startDate: "2024-02-01",
    endDate: formatDate(addDays(today, 25)),
    status: "expiring_soon",
    value: 150000,
    coverageType: "full",
    responseTime: "24 hours",
    coveredSerialNumbers: ["LIC-M365-ALPHA-001"],
    productIds: [],
    terms: "Microsoft 365 enterprise license agreement",
    autoRenew: true,
    renewalReminderDays: 45,
    createdBy: "USR001",
    createdAt: "2024-02-01",
    updatedAt: "2024-02-01"
  },
  {
    id: "CC003",
    contractNumber: "SATMZ-2024-CC-003",
    parentContractId: "PC002",
    parentContractNumber: "SATMZ-2024-PC-002",
    customerId: "CUST002",
    type: "Support",
    title: "Premium Support - Data Center",
    description: "24x7 premium support for data center equipment",
    startDate: "2024-02-15",
    endDate: formatDate(addDays(today, 300)),
    status: "active",
    value: 800000,
    coverageType: "full",
    responseTime: "2 hours",
    coveredSerialNumbers: ["SRV-2024-002001", "NET-2023-008765"],
    productIds: [],
    terms: "24x7 premium support with 2-hour response time",
    autoRenew: false,
    renewalReminderDays: 60,
    createdBy: "USR001",
    createdAt: "2024-02-15",
    updatedAt: "2024-02-15"
  },
  {
    id: "CC004",
    contractNumber: "SATMZ-2024-CC-004",
    parentContractId: "PC002",
    parentContractNumber: "SATMZ-2024-PC-002",
    customerId: "CUST002",
    type: "Extended Warranty",
    title: "Extended Warranty - Laptops",
    description: "Extended warranty coverage for all laptops",
    startDate: "2024-01-10",
    endDate: formatDate(addDays(today, 28)),
    status: "expiring_soon",
    value: 200000,
    coverageType: "full",
    responseTime: "Next Business Day",
    coveredSerialNumbers: ["LAP-2024-201"],
    productIds: [],
    terms: "Extended warranty coverage for all laptops",
    autoRenew: false,
    renewalReminderDays: 30,
    createdBy: "USR001",
    createdAt: "2024-01-10",
    updatedAt: "2024-01-10"
  },
  {
    id: "CC005",
    contractNumber: "SATMZ-2024-CC-005",
    parentContractId: "PC003",
    parentContractNumber: "SATMZ-2024-PC-003",
    customerId: "CUST003",
    type: "AMC",
    title: "Healthcare Equipment AMC",
    description: "AMC for medical IT infrastructure",
    startDate: "2024-03-01",
    endDate: formatDate(addDays(today, 45)),
    status: "expiring_soon",
    value: 350000,
    coverageType: "full",
    responseTime: "4 hours",
    coveredSerialNumbers: ["SRV-2023-003001", "LAP-2024-301"],
    productIds: [],
    terms: "AMC for medical IT infrastructure",
    autoRenew: true,
    renewalReminderDays: 45,
    createdBy: "USR001",
    createdAt: "2024-03-01",
    updatedAt: "2024-03-01"
  },
  {
    id: "CC006",
    contractNumber: "ALPHA-2024-CC-001",
    parentContractId: "PC004",
    parentContractNumber: "ALPHA-2024-PC-001",
    customerId: "CUST004",
    type: "AMC",
    title: "Financial Systems AMC",
    description: "AMC for banking infrastructure",
    startDate: "2024-04-01",
    endDate: formatDate(addDays(today, 200)),
    status: "active",
    value: 250000,
    coverageType: "full",
    responseTime: "2 hours",
    coveredSerialNumbers: ["SRV-2024-004001"],
    productIds: [],
    terms: "AMC for banking infrastructure",
    autoRenew: true,
    renewalReminderDays: 60,
    createdBy: "USR003",
    createdAt: "2024-04-01",
    updatedAt: "2024-04-01"
  },
  {
    id: "CC007",
    contractNumber: "ALPHA-2024-CC-002",
    parentContractId: "PC004",
    parentContractNumber: "ALPHA-2024-PC-001",
    customerId: "CUST004",
    type: "License",
    title: "Salesforce License Agreement",
    description: "CRM software licenses",
    startDate: "2024-01-01",
    endDate: formatDate(addDays(today, 55)),
    status: "expiring_soon",
    value: 180000,
    coverageType: "full",
    responseTime: "24 hours",
    coveredSerialNumbers: ["LIC-SF-DELTA-001"],
    productIds: [],
    terms: "CRM software licenses",
    autoRenew: true,
    renewalReminderDays: 30,
    createdBy: "USR003",
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01"
  },
  {
    id: "CC008",
    contractNumber: "ALPHA-2024-CC-003",
    parentContractId: "PC005",
    parentContractNumber: "ALPHA-2024-PC-002",
    customerId: "CUST005",
    type: "Support",
    title: "Development Support",
    description: "Technical support for dev infrastructure",
    startDate: "2024-05-15",
    endDate: formatDate(addDays(today, 15)),
    status: "expiring_soon",
    value: 120000,
    coverageType: "limited",
    responseTime: "8 hours",
    coveredSerialNumbers: ["LAP-2024-501", "LAP-2024-502"],
    productIds: [],
    terms: "Technical support for dev infrastructure",
    autoRenew: false,
    renewalReminderDays: 30,
    createdBy: "USR003",
    createdAt: "2024-05-15",
    updatedAt: "2024-05-15"
  },
  {
    id: "CC009",
    contractNumber: "BETA-2024-CC-001",
    parentContractId: "PC006",
    parentContractNumber: "BETA-2024-PC-001",
    customerId: "CUST006",
    type: "AMC",
    title: "Consulting IT AMC",
    description: "AMC for consulting equipment",
    startDate: "2024-06-01",
    endDate: formatDate(subDays(today, 10)),
    status: "expired",
    value: 100000,
    coverageType: "limited",
    responseTime: "Next Business Day",
    coveredSerialNumbers: ["LAP-2024-601"],
    productIds: [],
    terms: "AMC for consulting equipment",
    autoRenew: false,
    renewalReminderDays: 30,
    createdBy: "USR004",
    createdAt: "2024-06-01",
    updatedAt: "2024-06-01"
  }
];

export const dummyInventory: InventoryItem[] = [
  {
    id: "INV001",
    contractId: "PC001",
    contractNumber: "SATMZ-2024-PC-001",
    customerId: "CUST001",
    productName: "Dell PowerEdge R750 Server",
    serialNumber: "SRV-2024-001234",
    quantity: 2,
    unitPrice: 500000,
    totalPrice: 1000000,
    deliveryDate: "2024-01-15",
    warrantyStartDate: "2024-01-15",
    warrantyEndDate: formatDate(addDays(today, 400)),
    warrantyContractId: "CC001",
    licenseEndDate: null,
    licenseContractId: null,
    serviceType: "AMC",
    serviceStartDate: "2024-01-15",
    serviceEndDate: formatDate(addDays(today, 365)),
    serviceContractId: "CC001",
    category: "Server",
    manufacturer: "Dell",
    model: "PowerEdge R750",
    invoiceNumber: "INV-2024-0001",
    challanNumber: "DC-2024-0001",
    poNumber: "PO-2024-0001",
    status: "delivered",
    notes: "Rack mounted server with redundant PSU"
  },
  {
    id: "INV002",
    contractId: "PC001",
    contractNumber: "SATMZ-2024-PC-001",
    customerId: "CUST001",
    productName: "HP EliteBook 840 G9",
    serialNumber: "SRV-2024-001235",
    quantity: 10,
    unitPrice: 85000,
    totalPrice: 850000,
    deliveryDate: "2024-02-10",
    warrantyStartDate: "2024-02-10",
    warrantyEndDate: formatDate(addDays(today, 25)),
    warrantyContractId: "CC001",
    licenseEndDate: formatDate(addDays(today, 25)),
    licenseContractId: "CC002",
    serviceType: "Extended Support",
    serviceStartDate: "2024-02-10",
    serviceEndDate: formatDate(addDays(today, 180)),
    serviceContractId: "CC001",
    category: "Laptop",
    manufacturer: "HP",
    model: "EliteBook 840 G9",
    invoiceNumber: "INV-2024-0002",
    challanNumber: "DC-2024-0002",
    poNumber: "PO-2024-0002",
    status: "delivered",
    notes: "Business laptops with Windows 11 Pro"
  },
  {
    id: "INV003",
    contractId: "PC001",
    contractNumber: "SATMZ-2024-PC-001",
    customerId: "CUST001",
    productName: "Cisco Catalyst 9300 Switch",
    serialNumber: "NET-2024-003456",
    quantity: 5,
    unitPrice: 180000,
    totalPrice: 900000,
    deliveryDate: "2024-01-20",
    warrantyStartDate: "2024-01-20",
    warrantyEndDate: formatDate(addDays(today, 55)),
    warrantyContractId: null,
    licenseEndDate: null,
    licenseContractId: null,
    serviceType: "AMC",
    serviceStartDate: "2024-01-20",
    serviceEndDate: formatDate(addDays(today, 200)),
    serviceContractId: "CC001",
    category: "Networking Equipment",
    manufacturer: "Cisco",
    model: "Catalyst 9300",
    invoiceNumber: "INV-2024-0003",
    challanNumber: "DC-2024-0003",
    poNumber: "PO-2024-0003",
    status: "delivered",
    notes: "48-port managed switch"
  },
  {
    id: "INV004",
    contractId: "PC001",
    contractNumber: "SATMZ-2024-PC-001",
    customerId: "CUST001",
    productName: "Microsoft Office 365 E3",
    serialNumber: "LIC-M365-ALPHA-001",
    quantity: 50,
    unitPrice: 1200,
    totalPrice: 60000,
    deliveryDate: "2024-03-01",
    warrantyStartDate: null,
    warrantyEndDate: null,
    warrantyContractId: null,
    licenseEndDate: formatDate(addDays(today, 25)),
    licenseContractId: "CC002",
    serviceType: "Premium Support",
    serviceStartDate: "2024-03-01",
    serviceEndDate: formatDate(addDays(today, 25)),
    serviceContractId: "CC002",
    category: "Software License",
    manufacturer: "Microsoft",
    model: "Office 365 E3",
    invoiceNumber: "INV-2024-0004",
    challanNumber: "DC-2024-0004",
    poNumber: "PO-2024-0004",
    status: "delivered",
    notes: "Annual subscription licenses"
  },
  {
    id: "INV009",
    contractId: "PC002",
    contractNumber: "SATMZ-2024-PC-002",
    customerId: "CUST002",
    productName: "HPE ProLiant DL380 Gen10",
    serialNumber: "SRV-2024-002001",
    quantity: 3,
    unitPrice: 650000,
    totalPrice: 1950000,
    deliveryDate: "2024-02-20",
    warrantyStartDate: "2024-02-20",
    warrantyEndDate: formatDate(addDays(today, 300)),
    warrantyContractId: "CC003",
    licenseEndDate: null,
    licenseContractId: null,
    serviceType: "Premium Support",
    serviceStartDate: "2024-02-20",
    serviceEndDate: formatDate(addDays(today, 300)),
    serviceContractId: "CC003",
    category: "Server",
    manufacturer: "HPE",
    model: "ProLiant DL380 Gen10",
    invoiceNumber: "INV-2024-0009",
    challanNumber: "DC-2024-0009",
    poNumber: "PO-2024-0009",
    status: "delivered",
    notes: "Enterprise servers with 24x7 support"
  },
  {
    id: "INV010",
    contractId: "PC002",
    contractNumber: "SATMZ-2024-PC-002",
    customerId: "CUST002",
    productName: "Dell Latitude 7430",
    serialNumber: "LAP-2024-201",
    quantity: 25,
    unitPrice: 95000,
    totalPrice: 2375000,
    deliveryDate: "2024-02-25",
    warrantyStartDate: "2024-02-25",
    warrantyEndDate: formatDate(addDays(today, 28)),
    warrantyContractId: "CC004",
    licenseEndDate: null,
    licenseContractId: null,
    serviceType: "Extended Warranty",
    serviceStartDate: "2024-02-25",
    serviceEndDate: formatDate(addDays(today, 28)),
    serviceContractId: "CC004",
    category: "Laptop",
    manufacturer: "Dell",
    model: "Latitude 7430",
    invoiceNumber: "INV-2024-0010",
    challanNumber: "DC-2024-0010",
    poNumber: "PO-2024-0010",
    status: "delivered",
    notes: "Business laptops with extended warranty"
  },
  {
    id: "INV011",
    contractId: "PC002",
    contractNumber: "SATMZ-2024-PC-002",
    customerId: "CUST002",
    productName: "Fortinet FortiGate 600E",
    serialNumber: "NET-2023-008765",
    quantity: 2,
    unitPrice: 450000,
    totalPrice: 900000,
    deliveryDate: "2024-03-01",
    warrantyStartDate: "2024-03-01",
    warrantyEndDate: formatDate(addDays(today, 300)),
    warrantyContractId: "CC003",
    licenseEndDate: formatDate(addDays(today, 300)),
    licenseContractId: null,
    serviceType: "Premium Support",
    serviceStartDate: "2024-03-01",
    serviceEndDate: formatDate(addDays(today, 300)),
    serviceContractId: "CC003",
    category: "Networking Equipment",
    manufacturer: "Fortinet",
    model: "FortiGate 600E",
    invoiceNumber: "INV-2024-0011",
    challanNumber: "DC-2024-0011",
    poNumber: "PO-2024-0011",
    status: "delivered",
    notes: "Enterprise firewall with UTM"
  },
  {
    id: "INV016",
    contractId: "PC003",
    contractNumber: "SATMZ-2024-PC-003",
    customerId: "CUST003",
    productName: "Dell PowerEdge R650",
    serialNumber: "SRV-2023-003001",
    quantity: 2,
    unitPrice: 480000,
    totalPrice: 960000,
    deliveryDate: "2024-03-05",
    warrantyStartDate: "2024-03-05",
    warrantyEndDate: formatDate(addDays(today, 45)),
    warrantyContractId: "CC005",
    licenseEndDate: null,
    licenseContractId: null,
    serviceType: "AMC",
    serviceStartDate: "2024-03-05",
    serviceEndDate: formatDate(addDays(today, 45)),
    serviceContractId: "CC005",
    category: "Server",
    manufacturer: "Dell",
    model: "PowerEdge R650",
    invoiceNumber: "INV-2024-0016",
    challanNumber: "DC-2024-0016",
    poNumber: "PO-2024-0016",
    status: "delivered",
    notes: "Healthcare-compliant servers"
  },
  {
    id: "INV017",
    contractId: "PC003",
    contractNumber: "SATMZ-2024-PC-003",
    customerId: "CUST003",
    productName: "Lenovo ThinkPad X1 Carbon",
    serialNumber: "LAP-2024-301",
    quantity: 15,
    unitPrice: 120000,
    totalPrice: 1800000,
    deliveryDate: "2024-03-10",
    warrantyStartDate: "2024-03-10",
    warrantyEndDate: formatDate(addDays(today, 45)),
    warrantyContractId: "CC005",
    licenseEndDate: null,
    licenseContractId: null,
    serviceType: "AMC",
    serviceStartDate: "2024-03-10",
    serviceEndDate: formatDate(addDays(today, 45)),
    serviceContractId: "CC005",
    category: "Laptop",
    manufacturer: "Lenovo",
    model: "ThinkPad X1 Carbon",
    invoiceNumber: "INV-2024-0017",
    challanNumber: "DC-2024-0017",
    poNumber: "PO-2024-0017",
    status: "delivered",
    notes: "Ultralight business laptops"
  },
  {
    id: "INV018",
    contractId: "PC003",
    contractNumber: "SATMZ-2024-PC-003",
    customerId: "CUST003",
    productName: "HP Z2 Tower G9 Workstation",
    serialNumber: "WKS-2024-018901",
    quantity: 8,
    unitPrice: 180000,
    totalPrice: 1440000,
    deliveryDate: "2024-03-15",
    warrantyStartDate: "2024-03-15",
    warrantyEndDate: formatDate(addDays(today, 45)),
    warrantyContractId: null,
    licenseEndDate: null,
    licenseContractId: null,
    serviceType: null,
    serviceStartDate: null,
    serviceEndDate: null,
    serviceContractId: null,
    category: "Workstation",
    manufacturer: "HP",
    model: "Z2 Tower G9",
    invoiceNumber: "INV-2024-0018",
    challanNumber: "DC-2024-0018",
    poNumber: "PO-2024-0018",
    status: "delivered",
    notes: "High-performance workstations for imaging"
  },
  {
    id: "INV023",
    contractId: "PC004",
    contractNumber: "ALPHA-2024-PC-001",
    customerId: "CUST004",
    productName: "Dell PowerEdge R740",
    serialNumber: "SRV-2024-004001",
    quantity: 2,
    unitPrice: 550000,
    totalPrice: 1100000,
    deliveryDate: "2024-04-05",
    warrantyStartDate: "2024-04-05",
    warrantyEndDate: formatDate(addDays(today, 200)),
    warrantyContractId: "CC006",
    licenseEndDate: null,
    licenseContractId: null,
    serviceType: "AMC",
    serviceStartDate: "2024-04-05",
    serviceEndDate: formatDate(addDays(today, 200)),
    serviceContractId: "CC006",
    category: "Server",
    manufacturer: "Dell",
    model: "PowerEdge R740",
    invoiceNumber: "ALPHA-INV-001",
    challanNumber: "ALPHA-DC-001",
    poNumber: "ALPHA-PO-001",
    status: "delivered",
    notes: "Banking-grade servers"
  },
  {
    id: "INV024",
    contractId: "PC004",
    contractNumber: "ALPHA-2024-PC-001",
    customerId: "CUST004",
    productName: "NetApp FAS2750 Storage",
    serialNumber: "STO-2024-009012",
    quantity: 1,
    unitPrice: 800000,
    totalPrice: 800000,
    deliveryDate: "2024-04-10",
    warrantyStartDate: "2024-04-10",
    warrantyEndDate: formatDate(addDays(today, 200)),
    warrantyContractId: null,
    licenseEndDate: null,
    licenseContractId: null,
    serviceType: "Premium Support",
    serviceStartDate: "2024-04-10",
    serviceEndDate: formatDate(addDays(today, 200)),
    serviceContractId: "CC006",
    category: "Storage Device",
    manufacturer: "NetApp",
    model: "FAS2750",
    invoiceNumber: "ALPHA-INV-002",
    challanNumber: "ALPHA-DC-002",
    poNumber: "ALPHA-PO-002",
    status: "delivered",
    notes: "Enterprise storage array"
  },
  {
    id: "INV025",
    contractId: "PC004",
    contractNumber: "ALPHA-2024-PC-001",
    customerId: "CUST004",
    productName: "Salesforce CRM License",
    serialNumber: "LIC-SF-DELTA-001",
    quantity: 20,
    unitPrice: 30000,
    totalPrice: 600000,
    deliveryDate: "2024-04-15",
    warrantyStartDate: null,
    warrantyEndDate: null,
    warrantyContractId: null,
    licenseEndDate: formatDate(addDays(today, 55)),
    licenseContractId: "CC007",
    serviceType: "Standard Support",
    serviceStartDate: "2024-04-15",
    serviceEndDate: formatDate(addDays(today, 55)),
    serviceContractId: "CC007",
    category: "Software License",
    manufacturer: "Salesforce",
    model: "Sales Cloud",
    invoiceNumber: "ALPHA-INV-003",
    challanNumber: "ALPHA-DC-003",
    poNumber: "ALPHA-PO-003",
    status: "delivered",
    notes: "CRM licenses for sales team"
  },
  {
    id: "INV031",
    contractId: "PC005",
    contractNumber: "ALPHA-2024-PC-002",
    customerId: "CUST005",
    productName: "Apple MacBook Pro 16-inch",
    serialNumber: "LAP-2024-501",
    quantity: 10,
    unitPrice: 250000,
    totalPrice: 2500000,
    deliveryDate: "2024-05-20",
    warrantyStartDate: "2024-05-20",
    warrantyEndDate: formatDate(addDays(today, 15)),
    warrantyContractId: "CC008",
    licenseEndDate: null,
    licenseContractId: null,
    serviceType: "Development Support",
    serviceStartDate: "2024-05-20",
    serviceEndDate: formatDate(addDays(today, 15)),
    serviceContractId: "CC008",
    category: "Laptop",
    manufacturer: "Apple",
    model: "MacBook Pro 16-inch",
    invoiceNumber: "ALPHA-INV-004",
    challanNumber: "ALPHA-DC-004",
    poNumber: "ALPHA-PO-004",
    status: "delivered",
    notes: "Development workstations"
  },
  {
    id: "INV032",
    contractId: "PC005",
    contractNumber: "ALPHA-2024-PC-002",
    customerId: "CUST005",
    productName: "Dell UltraSharp U2720Q Monitor",
    serialNumber: "LAP-2024-502",
    quantity: 20,
    unitPrice: 45000,
    totalPrice: 900000,
    deliveryDate: "2024-05-22",
    warrantyStartDate: "2024-05-22",
    warrantyEndDate: formatDate(addDays(today, 15)),
    warrantyContractId: null,
    licenseEndDate: null,
    licenseContractId: null,
    serviceType: null,
    serviceStartDate: null,
    serviceEndDate: null,
    serviceContractId: null,
    category: "Monitor",
    manufacturer: "Dell",
    model: "UltraSharp U2720Q",
    invoiceNumber: "ALPHA-INV-005",
    challanNumber: "ALPHA-DC-005",
    poNumber: "ALPHA-PO-005",
    status: "delivered",
    notes: "4K monitors for developers"
  },
  {
    id: "INV033",
    contractId: "PC006",
    contractNumber: "BETA-2024-PC-001",
    customerId: "CUST006",
    productName: "HP EliteDesk 800 G9",
    serialNumber: "LAP-2024-601",
    quantity: 15,
    unitPrice: 75000,
    totalPrice: 1125000,
    deliveryDate: "2024-06-05",
    warrantyStartDate: "2024-06-05",
    warrantyEndDate: formatDate(subDays(today, 10)),
    warrantyContractId: "CC009",
    licenseEndDate: null,
    licenseContractId: null,
    serviceType: "AMC",
    serviceStartDate: "2024-06-05",
    serviceEndDate: formatDate(subDays(today, 10)),
    serviceContractId: "CC009",
    category: "Desktop",
    manufacturer: "HP",
    model: "EliteDesk 800 G9",
    invoiceNumber: "BETA-INV-001",
    challanNumber: "BETA-DC-001",
    poNumber: "BETA-PO-001",
    status: "delivered",
    notes: "Business desktops"
  },
  {
    id: "INV034",
    contractId: "PC006",
    contractNumber: "BETA-2024-PC-001",
    customerId: "CUST006",
    productName: "Logitech MeetUp Camera",
    serialNumber: "CAM-2024-021234",
    quantity: 5,
    unitPrice: 75000,
    totalPrice: 375000,
    deliveryDate: "2024-06-08",
    warrantyStartDate: "2024-06-08",
    warrantyEndDate: formatDate(subDays(today, 10)),
    warrantyContractId: null,
    licenseEndDate: null,
    licenseContractId: null,
    serviceType: null,
    serviceStartDate: null,
    serviceEndDate: null,
    serviceContractId: null,
    category: "Conference Equipment",
    manufacturer: "Logitech",
    model: "MeetUp",
    invoiceNumber: "BETA-INV-002",
    challanNumber: "BETA-DC-002",
    poNumber: "BETA-PO-002",
    status: "delivered",
    notes: "Conference room cameras"
  }
];

export const dummyTickets: Ticket[] = [
  {
    id: "TKT001",
    customerId: "CUST001",
    contractId: "PC001",
    contractNumber: "SATMZ-2024-PC-001",
    serialNumber: "SRV-2024-001234",
    productName: "Dell PowerEdge R750 Server",
    category: "Hardware Issue",
    priority: "high",
    subject: "Server overheating warning",
    description: "Getting temperature warning alerts on server dashboard. Fan speeds appear normal but temperature keeps rising.",
    status: "open",
    warrantyStatus: "active",
    serviceStatus: "covered",
    coverageDetails: "Under AMC - 4 hour response time",
    createdAt: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 2, 10, 30).toISOString(),
    updatedAt: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 2, 10, 30).toISOString(),
    resolvedAt: null,
    assignedTo: null,
    timeline: [
      {
        action: "Ticket Created",
        by: "Alpha Business Solutions",
        at: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 2, 10, 30).toISOString(),
        note: "Initial ticket submission"
      }
    ]
  },
  {
    id: "TKT002",
    customerId: "CUST002",
    contractId: "PC002",
    contractNumber: "SATMZ-2024-PC-002",
    serialNumber: "NET-2023-008765",
    productName: "Fortinet FortiGate 600E",
    category: "Network Issue",
    priority: "critical",
    subject: "Network connectivity dropping intermittently",
    description: "Firewall is dropping connections every few hours. Affecting production systems.",
    status: "in_progress",
    warrantyStatus: "active",
    serviceStatus: "covered",
    coverageDetails: "Under Premium Support - 2 hour response time",
    createdAt: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 5, 14, 15).toISOString(),
    updatedAt: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 1, 9, 0).toISOString(),
    resolvedAt: null,
    assignedTo: "Network Team",
    timeline: [
      {
        action: "Ticket Created",
        by: "Beta Corporation",
        at: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 5, 14, 15).toISOString(),
        note: "Initial ticket submission"
      },
      {
        action: "Status Updated to In Progress",
        by: "Support Team",
        at: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 4, 10, 0).toISOString(),
        note: "Assigned to network specialist. Investigating firmware version."
      },
      {
        action: "Comment Added",
        by: "Support Team",
        at: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 1, 9, 0).toISOString(),
        note: "Firmware update scheduled for tonight. Will monitor post-update."
      }
    ]
  },
  {
    id: "TKT003",
    customerId: "CUST001",
    contractId: "PC001",
    contractNumber: "SATMZ-2024-PC-001",
    serialNumber: "SRV-2024-001235",
    productName: "HP EliteBook 840 G9",
    category: "Software Issue",
    priority: "medium",
    subject: "Windows 11 update causing BSOD",
    description: "After latest Windows update, laptop experiencing blue screen errors randomly.",
    status: "resolved",
    warrantyStatus: "expiring_soon",
    serviceStatus: "covered",
    coverageDetails: "Under Extended Support - Next Business Day response",
    createdAt: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 10, 11, 20).toISOString(),
    updatedAt: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 3, 16, 45).toISOString(),
    resolvedAt: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 3, 16, 45).toISOString(),
    assignedTo: "Software Team",
    timeline: [
      {
        action: "Ticket Created",
        by: "Alpha Business Solutions",
        at: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 10, 11, 20).toISOString(),
        note: "Initial ticket submission"
      },
      {
        action: "Status Updated to In Progress",
        by: "Support Team",
        at: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 9, 9, 30).toISOString(),
        note: "Investigating driver compatibility issues."
      },
      {
        action: "Comment Added",
        by: "Support Team",
        at: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 7, 14, 0).toISOString(),
        note: "Identified graphics driver conflict. Updated drivers remotely."
      },
      {
        action: "Status Updated to Resolved",
        by: "Support Team",
        at: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 3, 16, 45).toISOString(),
        note: "Issue resolved. Customer confirmed stable operation for 4 days."
      }
    ]
  },
  {
    id: "TKT004",
    customerId: "CUST004",
    contractId: "PC004",
    contractNumber: "ALPHA-2024-PC-001",
    serialNumber: "LIC-SF-DELTA-001",
    productName: "Salesforce CRM License",
    category: "License Issue",
    priority: "high",
    subject: "License activation failing for 3 users",
    description: "Unable to activate Salesforce licenses for 3 new employees. Getting error code 401.",
    status: "open",
    warrantyStatus: "not_applicable",
    serviceStatus: "covered",
    coverageDetails: "Under License Agreement - 24 hour response time",
    createdAt: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 1, 15, 10).toISOString(),
    updatedAt: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 1, 15, 10).toISOString(),
    resolvedAt: null,
    assignedTo: null,
    timeline: [
      {
        action: "Ticket Created",
        by: "Delta Systems",
        at: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 1, 15, 10).toISOString(),
        note: "Initial ticket submission"
      }
    ]
  }
];

export const dummyNotifications: Notification[] = [
  {
    id: "NOT001",
    customerId: "CUST001",
    type: "warranty_expiry",
    title: "Contract Expiring Soon",
    message: "Child Contract CC-002 (Microsoft 365 License Agreement) expires in 25 days",
    serialNumber: "LIC-M365-ALPHA-001",
    isRead: false,
    createdAt: new Date(today.getFullYear(), today.getMonth(), today.getDate(), 8, 0).toISOString()
  },
  {
    id: "NOT002",
    customerId: "CUST001",
    type: "ticket_update",
    title: "Ticket Update",
    message: "Your ticket TKT003 has been resolved",
    isRead: true,
    createdAt: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 3, 16, 45).toISOString()
  },
  {
    id: "NOT003",
    customerId: "CUST002",
    type: "warranty_expiry",
    title: "Contract Expiring Soon",
    message: "Child Contract CC-004 (Extended Warranty - Laptops) expires in 28 days",
    serialNumber: "LAP-2024-201",
    isRead: false,
    createdAt: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 1, 8, 0).toISOString()
  },
  {
    id: "NOT004",
    customerId: "CUST003",
    type: "warranty_expiry",
    title: "Parent Contract Expiring Soon",
    message: "Parent Contract SATMZ-2024-PC-003 (Healthcare IT Solutions) expires in 45 days",
    isRead: false,
    createdAt: new Date(today.getFullYear(), today.getMonth(), today.getDate(), 8, 0).toISOString()
  },
  {
    id: "NOT005",
    customerId: "CUST004",
    type: "license_expiry",
    title: "License Renewal Required",
    message: "Child Contract CC-007 (Salesforce License Agreement) expires in 55 days",
    serialNumber: "LIC-SF-DELTA-001",
    isRead: false,
    createdAt: new Date(today.getFullYear(), today.getMonth(), today.getDate(), 8, 0).toISOString()
  },
  {
    id: "NOT006",
    customerId: "CUST005",
    type: "warranty_expiry",
    title: "Contract Expiring Very Soon",
    message: "Parent Contract ALPHA-2024-PC-002 (Software Development Infrastructure) expires in 15 days",
    isRead: false,
    createdAt: new Date(today.getFullYear(), today.getMonth(), today.getDate(), 8, 0).toISOString()
  },
  {
    id: "NOT007",
    customerId: "CUST006",
    type: "warranty_expiry",
    title: "Contract Expired",
    message: "Parent Contract BETA-2024-PC-001 (Consulting IT Infrastructure) has expired",
    isRead: false,
    createdAt: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 10, 8, 0).toISOString()
  },
  {
    id: "NOT008",
    customerId: null,
    type: "system",
    title: "System Maintenance",
    message: "Scheduled maintenance on Saturday 2 AM - 4 AM IST",
    isRead: true,
    createdAt: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 7, 12, 0).toISOString()
  }
];

export const loginCredentials = {
  "admin@satmz.com": { password: "admin123", userId: "USR001" },
  "manager@satmz.com": { password: "manager123", userId: "USR002" },
  "reseller1@satmz.com": { password: "reseller123", userId: "USR003" },
  "reseller2@satmz.com": { password: "reseller123", userId: "USR004" },
  "customer1@satmz.com": { password: "customer123", userId: "USR005" },
  "customer2@satmz.com": { password: "customer123", userId: "USR006" },
  "customer3@satmz.com": { password: "customer123", userId: "USR007" },
  "customer4@satmz.com": { password: "customer123", userId: "USR008" }
};

export function initializeLocalStorage() {
  if (typeof window === "undefined") return;
  
  if (!localStorage.getItem("inventory_customers")) {
    localStorage.setItem("inventory_customers", JSON.stringify(dummyCustomers));
  }
  
  if (!localStorage.getItem("inventory_items")) {
    localStorage.setItem("inventory_items", JSON.stringify(dummyInventory));
  }
  
  if (!localStorage.getItem("inventory_tickets")) {
    localStorage.setItem("inventory_tickets", JSON.stringify(dummyTickets));
  }
  
  if (!localStorage.getItem("inventory_notifications")) {
    localStorage.setItem("inventory_notifications", JSON.stringify(dummyNotifications));
  }
  
  if (!localStorage.getItem("inventory_users")) {
    localStorage.setItem("inventory_users", JSON.stringify(dummyUsers));
  }
  
  if (!localStorage.getItem("inventory_parent_contracts")) {
    localStorage.setItem("inventory_parent_contracts", JSON.stringify(dummyParentContracts));
  }
  
  if (!localStorage.getItem("inventory_child_contracts")) {
    localStorage.setItem("inventory_child_contracts", JSON.stringify(dummyChildContracts));
  }
}
